### ISSUE TITLE
Sandpit helloworld

### ISSUE THREAD

**Issue by fprotais** [ssloy/stlbfgs#2]
`add_executable(helloworld helloworld.cpp)` <- may conflicts with projects containing helloworlds including this project . I recommand:
`add_executable(stlbfgs_helloworldhelloworld.cpp)`

**Comment by ssloy** [comment]
fixed in this commit
https://github.com/ssloy/stlbfgs/commit/2fe75cf4a9369ac6e1da7865741ded68dc7132db
